### ISSUE TITLE
Allow .s scp-number

### ISSUE THREAD

**Issue by rossjrw** [CCastellano/HelenBot#36]
Helen will happily search for "scp-xxxx" as a message by itself, but she won't find anything for ".s scp-xxxx". Given a bot whose purpose is to search the scp wiki, this seems like an oversight

This could possibly be done in Command.java by calling scpSearch() from findSkip() if the search matches the regex?

**Comment by CCastellano** [comment]
This is an issue due to the technical implementation of .s.  I'm not particularly interested in fixing this.
